const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Job = require('./models/Job');

dotenv.config();

const connectDB = require('./config/database');

const dummyJobs = [
    {
        company_name: 'Blue Kaktus',
        job_title: 'Manager - Business Development(B2B SaaS, ERP, Manufacturing)',
        job_id: '6715',
        posted_date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000), // 30 days ago
        locations: ['Chennai', '1 other'],
        salary_min: 1100000,
        salary_max: 1500000,
        experience_min: 5,
        experience_max: 7,
        notice_period: 60,
        num_positions: 3,
        relevant_level: 1.71,
        applications_required: 18,
        in_process_applications: 2,
        commission_percent: 3,
        commission_amount_min: 34000,
        commission_amount_max: 45000,
        commission_payment_terms: '75 to 90 Days',
        r1_bonus_amount: 250,
        r1_bonus_payment_terms: '7 to 14 Days',
        role_status: 'Active',
        sourcing_status: 'Priority',
        description: 'This is a dummy job description for Manager - Business Development.',
        requirements: 'Experience in B2B SaaS, ERP, Manufacturing.',
        skills: ['Sales', 'B2B', 'SaaS', 'ERP']
    },
    {
        company_name: 'Tech Solutions',
        job_title: 'Senior Software Engineer (React, Node.js)',
        job_id: '6716',
        posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 days ago
        locations: ['Bangalore', 'Remote'],
        salary_min: 2000000,
        salary_max: 3000000,
        experience_min: 4,
        experience_max: 8,
        notice_period: 30,
        num_positions: 5,
        relevant_level: 2.0,
        applications_required: 25,
        in_process_applications: 5,
        commission_percent: 5,
        commission_amount_min: 50000,
        commission_amount_max: 70000,
        commission_payment_terms: '30 to 45 Days',
        r1_bonus_amount: 500,
        r1_bonus_payment_terms: '7 Days',
        role_status: 'Active',
        sourcing_status: 'Priority',
        description: 'Looking for a Senior Software Engineer with expertise in MERN stack.',
        requirements: 'Strong proficiency in JavaScript, React, and Node.js.',
        skills: ['React', 'Node.js', 'MongoDB', 'AWS']
    },
    {
        company_name: 'DataCorp Analytics',
        job_title: 'Data Analyst (Python, SQL, Tableau)',
        job_id: '6717',
        posted_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000), // 10 days ago
        locations: ['Mumbai', 'Pune'],
        salary_min: 800000,
        salary_max: 1200000,
        experience_min: 2,
        experience_max: 5,
        notice_period: 45,
        num_positions: 4,
        relevant_level: 1.5,
        applications_required: 20,
        in_process_applications: 3,
        commission_percent: 4,
        commission_amount_min: 32000,
        commission_amount_max: 48000,
        commission_payment_terms: '60 Days',
        r1_bonus_amount: 300,
        r1_bonus_payment_terms: '10 Days',
        role_status: 'Active',
        sourcing_status: 'Priority',
        description: 'Seeking a Data Analyst with strong analytical and visualization skills.',
        requirements: 'Proficiency in Python, SQL, and data visualization tools.',
        skills: ['Python', 'SQL', 'Tableau', 'Excel', 'Data Analysis']
    },
    {
        company_name: 'CloudTech Innovations',
        job_title: 'DevOps Engineer (AWS, Kubernetes, Docker)',
        job_id: '6718',
        posted_date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000), // 15 days ago
        locations: ['Hyderabad', 'Remote'],
        salary_min: 1500000,
        salary_max: 2500000,
        experience_min: 3,
        experience_max: 6,
        notice_period: 30,
        num_positions: 3,
        relevant_level: 1.8,
        applications_required: 15,
        in_process_applications: 4,
        commission_percent: 5,
        commission_amount_min: 45000,
        commission_amount_max: 75000,
        commission_payment_terms: '45 Days',
        r1_bonus_amount: 400,
        r1_bonus_payment_terms: '7 Days',
        role_status: 'Active',
        sourcing_status: 'Priority',
        description: 'Looking for a DevOps Engineer to manage cloud infrastructure.',
        requirements: 'Experience with AWS, Kubernetes, Docker, and CI/CD pipelines.',
        skills: ['AWS', 'Kubernetes', 'Docker', 'Jenkins', 'Terraform']
    },
    {
        company_name: 'FinServe Solutions',
        job_title: 'Product Manager (Fintech)',
        job_id: '6719',
        posted_date: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000), // 20 days ago
        locations: ['Delhi', 'Gurgaon'],
        salary_min: 2500000,
        salary_max: 3500000,
        experience_min: 6,
        experience_max: 10,
        notice_period: 60,
        num_positions: 2,
        relevant_level: 2.2,
        applications_required: 10,
        in_process_applications: 2,
        commission_percent: 6,
        commission_amount_min: 75000,
        commission_amount_max: 105000,
        commission_payment_terms: '90 Days',
        r1_bonus_amount: 600,
        r1_bonus_payment_terms: '14 Days',
        role_status: 'Active',
        sourcing_status: 'Normal',
        description: 'Seeking an experienced Product Manager for fintech products.',
        requirements: 'Strong background in fintech, product strategy, and stakeholder management.',
        skills: ['Product Management', 'Fintech', 'Agile', 'Strategy', 'Analytics']
    },
    {
        company_name: 'Digital Marketing Pro',
        job_title: 'Digital Marketing Manager (SEO, SEM, Social Media)',
        job_id: '6720',
        posted_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000), // 7 days ago
        locations: ['Bangalore', 'Chennai'],
        salary_min: 900000,
        salary_max: 1400000,
        experience_min: 4,
        experience_max: 7,
        notice_period: 45,
        num_positions: 2,
        relevant_level: 1.6,
        applications_required: 12,
        in_process_applications: 1,
        commission_percent: 4,
        commission_amount_min: 36000,
        commission_amount_max: 56000,
        commission_payment_terms: '60 Days',
        r1_bonus_amount: 350,
        r1_bonus_payment_terms: '10 Days',
        role_status: 'Active',
        sourcing_status: 'Priority',
        description: 'Looking for a Digital Marketing Manager to drive online growth.',
        requirements: 'Expertise in SEO, SEM, social media marketing, and analytics.',
        skills: ['SEO', 'SEM', 'Social Media', 'Google Analytics', 'Content Marketing']
    },
    {
        company_name: 'MobileTech Apps',
        job_title: 'iOS Developer (Swift, SwiftUI)',
        job_id: '6721',
        posted_date: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000), // 12 days ago
        locations: ['Pune', 'Remote'],
        salary_min: 1200000,
        salary_max: 1800000,
        experience_min: 3,
        experience_max: 6,
        notice_period: 30,
        num_positions: 4,
        relevant_level: 1.7,
        applications_required: 16,
        in_process_applications: 3,
        commission_percent: 4.5,
        commission_amount_min: 40000,
        commission_amount_max: 60000,
        commission_payment_terms: '45 Days',
        r1_bonus_amount: 400,
        r1_bonus_payment_terms: '7 Days',
        role_status: 'Active',
        sourcing_status: 'Priority',
        description: 'Seeking an iOS Developer to build innovative mobile applications.',
        requirements: 'Strong experience with Swift, SwiftUI, and iOS frameworks.',
        skills: ['Swift', 'SwiftUI', 'iOS', 'Xcode', 'RESTful APIs']
    },
    {
        company_name: 'AI Innovations Lab',
        job_title: 'Machine Learning Engineer (Python, TensorFlow)',
        job_id: '6722',
        posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
        locations: ['Bangalore', 'Hyderabad'],
        salary_min: 1800000,
        salary_max: 2800000,
        experience_min: 3,
        experience_max: 7,
        notice_period: 30,
        num_positions: 3,
        relevant_level: 2.1,
        applications_required: 15,
        in_process_applications: 5,
        commission_percent: 5.5,
        commission_amount_min: 55000,
        commission_amount_max: 85000,
        commission_payment_terms: '60 Days',
        r1_bonus_amount: 500,
        r1_bonus_payment_terms: '7 Days',
        role_status: 'Active',
        sourcing_status: 'Priority',
        description: 'Looking for an ML Engineer to develop cutting-edge AI solutions.',
        requirements: 'Experience with Python, TensorFlow, deep learning, and model deployment.',
        skills: ['Python', 'TensorFlow', 'Machine Learning', 'Deep Learning', 'PyTorch']
    },
    {
        company_name: 'CyberSecure Systems',
        job_title: 'Cybersecurity Analyst (Network Security, Penetration Testing)',
        job_id: '6723',
        posted_date: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000), // 18 days ago
        locations: ['Mumbai', 'Delhi'],
        salary_min: 1000000,
        salary_max: 1600000,
        experience_min: 2,
        experience_max: 5,
        notice_period: 45,
        num_positions: 3,
        relevant_level: 1.5,
        applications_required: 12,
        in_process_applications: 2,
        commission_percent: 4,
        commission_amount_min: 40000,
        commission_amount_max: 64000,
        commission_payment_terms: '60 Days',
        r1_bonus_amount: 350,
        r1_bonus_payment_terms: '10 Days',
        role_status: 'Active',
        sourcing_status: 'Normal',
        description: 'Seeking a Cybersecurity Analyst to protect our digital assets.',
        requirements: 'Knowledge of network security, penetration testing, and security frameworks.',
        skills: ['Network Security', 'Penetration Testing', 'SIEM', 'Firewall', 'Ethical Hacking']
    },
    {
        company_name: 'HR Tech Solutions',
        job_title: 'HR Business Partner (Talent Acquisition, Employee Relations)',
        job_id: '6724',
        posted_date: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000), // 25 days ago
        locations: ['Chennai', 'Bangalore'],
        salary_min: 1100000,
        salary_max: 1700000,
        experience_min: 5,
        experience_max: 8,
        notice_period: 60,
        num_positions: 2,
        relevant_level: 1.6,
        applications_required: 10,
        in_process_applications: 1,
        commission_percent: 4,
        commission_amount_min: 44000,
        commission_amount_max: 68000,
        commission_payment_terms: '75 Days',
        r1_bonus_amount: 300,
        r1_bonus_payment_terms: '14 Days',
        role_status: 'Active',
        sourcing_status: 'Normal',
        description: 'Looking for an HR Business Partner to support organizational growth.',
        requirements: 'Experience in talent acquisition, employee relations, and HR strategy.',
        skills: ['HR Management', 'Talent Acquisition', 'Employee Relations', 'HRIS', 'Compliance']
    }
];

const seedJobs = async () => {
    try {
        await connectDB();
        await Job.deleteMany(); // Clear existing jobs
        await Job.insertMany(dummyJobs);
        const count = await Job.countDocuments();
        console.log(`Dummy jobs imported! Total jobs: ${count}`);
        process.exit();
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
};

seedJobs();
